import { Controller, Get, UsePipes,ValidationPipe } from '@nestjs/common';
import { ProductsService } from './products.service';
import { EventPattern, MessagePattern } from '@nestjs/microservices';
import { CreateProductDto } from './dtos/createProducts.dto';
import { GetProductByIdDto } from './dtos/getProductById.dto';
import { GetProductsInfoByIdsDto } from './dtos/getProductsInfoByIds.dto';
import { EditPriceDto } from './dtos/editPrice.dto';
import { GetPriceHistoryDto } from './dtos/getPriceHistory.dto';
import { ProductEntity } from './entities/product.entity';

@Controller()
export class ProductsController {
  constructor(private readonly productsService: ProductsService) {}
  @MessagePattern({cmd : 'product_created'})
  async createProduct(product: CreateProductDto) {
   const savedProduct:ProductEntity = await this.productsService.createProduct(product);
   const autogeneratedProductId = savedProduct.id
   return autogeneratedProductId
  } 
   @MessagePattern({ cmd: 'product-by-id' })
   getProductById(data:GetProductByIdDto) {
      console.log(data)
      const productId = data.productId.id
      console.log(typeof productId)
      return this.productsService.getProductById(productId)
   }
   @MessagePattern({cmd : 'products-info'})
   getProductsInfoByIds(data : GetProductsInfoByIdsDto){
      
      const producstIds = data.productsIds
      
      return this.productsService.getProductsInfoByIds(producstIds)
      
   }
   @EventPattern('price-edited')
   EditProductPrice(editPriceDto: EditPriceDto) {
    
     return this.productsService.editProductPrice(editPriceDto)
  } 
  @MessagePattern({cmd : 'get-price-history'})
  async getPriceHistoryById(data : GetPriceHistoryDto ){
   
   console.log('this is the data: ',data)
   const productId = data.productId.id
   const history = await this.productsService.getPriceHistoryById(productId)
   console.log('from the controller',history)
   return history
  }
}
